---
apiVersion: "kafka.aiven.io/v1beta1"
kind: "KafkaTopicAclEntry"
metadata:
  labels: {}
  annotations:
    aiven.io/kafka-acl-id: "default"
spec:
  permission: "ADMIN"
  username: "avnadmin"
  topic: "*"
---
apiVersion: "kafka.aiven.io/v1beta2"
kind: "KafkaTopicAclEntry"
metadata:
  labels: {}
  spec:
    permission: "READWRITE"
    username: "alice"
    topic: "*alice*"