---
apiVersion: "kafka.aiven.io/v1beta1"
kind: "KafkaQuota"
spec:
  user: "default"
  clientId: "default"
  consumerByteRate: 1048576
  producerByteRate: 1048576
  requestPercentage: 25
---
apiVersion: "kafka.aiven.io/v1beta2"
kind: "KafkaQuota"
spec:
  user: "avdnadmin"
  consumerByteRate: 1048576