---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: KafkaTopicList
metadata:
  labels: 
    environment: example
items:
  - metadata:
      name: 'my-topic-p3-r1'
    spec:
      partitions: 3
      replicas: 1
    configs:
      min.insync.replicas: 1
      cleanup.policy: 'delete'

  - metadata:
      name: 'test'
    spec:
      partitions: 1
      replicas: 1
      configs:
        min.insync.replicas: 1
        cleanup.policy: 'compact'

