name: Deploy Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          check-latest: true
          cache: maven

      - name: Set env VERSION
        run: |
          VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check VERSION
        run: echo "${{ env.VERSION }}"

      - name: Init Setting.xml
        run: |
          echo "<settings><interactiveMode>false</interactiveMode><servers><server><id>ossrh</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_PASSWORD }}</password></server><servers></settings>" > ./settings.xml

      - name: Grant execute permission to MVN Wrapper
        run: chmod +x ./mvnw

      - name: Deploy Maven Central
        run: |
          ./mvnw -s ./settings.xml deploy -Possrh
