name: Releases Manually

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          check-latest: true
          cache: maven

      - name: Set env VERSION
        run: |
          VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check VERSION
        run: echo "${{ env.VERSION }}"

      - name: Init Setting.xml
        run: |
          echo "<settings><interactiveMode>false</interactiveMode><server><id>ossrh</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_PASSWORD }}</password></server></settings>" > settings.xml

      - name: Grant execute permission to MVN Wrapper
        run: chmod +x ./mvnw

      - name: Build Distributions
        run: |
          ./mvnw -s ./settings.xml clean package -Pdist -DskipTests
          sha1sum ./dist/jikkou.deb > ./dist/jikkou.deb.sha1
          sha1sum ./dist/jikkou-${{ env.VERSION }}-runner.tar.gz > ./dist/jikkou-${{ env.VERSION }}-runner.tar.gz.sha1
          sha1sum ./dist/jikkou-${{ env.VERSION }}-runner.zip > ./dist/jikkou-${{ env.VERSION }}-runner.zip.sha1

      - name: Deploy Maven Central
        run: |
          ./mvnw -s ./settings.xml deploy -Possrh

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: RELEASE-${{env.VERSION}}
          draft: false
          artifacts: "./dist/jikkou.deb,./dist/jikkou.deb.sha1,./dist/jikkou-${{ env.VERSION }}-runner.tar.gz,./dist/jikkou-${{ env.VERSION }}-runner.tar.gz.sha1,./dist/jikkou-${{ env.VERSION }}-runner.zip,./dist/jikkou-${{ env.VERSION }}-runner.zip.sha1"
          prerelease: false
