name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          check-latest: true
          cache: maven

      - name: Grant execute permission to MVN Wrapper
        run: chmod +x ./mvnw

      - name: Build Distributions
        run: |
          ./mvnw clean package -Pdist -DskipTests
          sha1sum ./dist/jikkou.deb > ./dist/jikkou.deb.sha1
          sha1sum ./dist/jikkou-${{ env.VERSION }}-runner.tar.gz > ./dist/jikkou-${{ env.VERSION }}-runner.tar.gz.sha1
          sha1sum ./dist/jikkou-${{ env.VERSION }}-runner.zip > ./dist/jikkou-${{ env.VERSION }}-runner.zip.sha1

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: ${{ github.event.inputs.releaseName }} ${{env.VERSION}}
          draft: false
          artifacts: "./dist/jikkou.deb,./dist/jikkou.deb.sha1,./dist/jikkou-${{ env.VERSION }}-runner.tar.gz,./dist/jikkou-${{ env.VERSION }}-runner.tar.gz.sha1,./dist/jikkou-${{ env.VERSION }}-runner.zip,./dist/jikkou-${{ env.VERSION }}-runner.zip.sha1"
          prerelease: false
